version: "3.8"
services:
  web:
    build: .
    platform: linux/amd64
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: askmybook_dev
      PGPORT: 5432
      PGHOST: db
      OPENAI_API_KEY: "sk-rMAzgGXLelyktW5v6PHdsjaldjsak"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
